# Generated by Django 5.2.14 on 2026-10-06 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="s3filepermissions",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("view_s3file", "Can view S3 files"),
                    ("delete_s3file", "Can delete S3 files"),
                ],
                "verbose_name": "S3 file",
                "verbose_name_plural": "S3 files",
            },
        ),
    ]
