# Generated by Django 5.2.14 on 2026-07-16 16:06

import crud_views_workflow.lib.mixins
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
            ],
            bases=(crud_views_workflow.lib.mixins.WorkflowModelMixin, models.Model),
        ),
    ]
