# Generated by Django 5.2.14 on 2026-10-06 09:12

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={"verbose_name": "campaign", "verbose_name_plural": "campaigns"},
        ),
        migrations.AlterField(
            model_name="campaign",
            name="name",
            field=models.CharField(max_length=128, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("error", "Error"),
                ],
                default="draft",
                max_length=50,
                verbose_name="state",
            ),
        ),
    ]
