# Generated by Django 5.2.14 on 2026-10-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formsets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={
                "ordering": ("order",),
                "verbose_name": "choice",
                "verbose_name_plural": "choices",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("order",),
                "verbose_name": "question",
                "verbose_name_plural": "questions",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnaire",
            options={
                "ordering": ["title"],
                "verbose_name": "questionnaire",
                "verbose_name_plural": "questionnaires",
            },
        ),
        migrations.AlterField(
            model_name="choice",
            name="label",
            field=models.CharField(max_length=100, verbose_name="label"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="formsets.question",
                verbose_name="question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="formsets.questionnaire",
                verbose_name="questionnaire",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=200, verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
    ]
