version: '3'

vars:
  PYTHON: "3.12"

tasks:

  dev:
    cmds:
      - task: dev-venv
      - task: dev-install

  dev-venv:
    cmds:
      - uv venv --python={{ .PYTHON }} --clear
    silent: true

  dev-install:
    cmds:
      - uv pip install --upgrade .[polymorphic,workflow,dev,test]
    silent: true

  format:
    cmds:
      - uv run ruff format .
    silent: true

  build:
    cmds:
      - uv build
    silent: true

  docs:
    cmds:
      - mkdocs serve -a localhost:8001
    silent: true

  cleanup:
    cmds:
      - find . -type d -name "__pycache__" -exec rm -r {} +
      - rm -rf .nox dist
    silent: true

  bump-patch:
    cmds:
      - bumpver update --patch --no-fetch
    silent: true

  test:
    cmds:
      - uv run nox -p
      - rm -rf .nox
    silent: true
