# Generated by Django 6.0.7 on 2026-07-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conditional", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="with_speakers",
            field=models.BooleanField(default=False, verbose_name="Show speaker line-up"),
        ),
        migrations.AddField(
            model_name="registration",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="conditional.event",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
