# Generated by Django 5.2.14 on 2026-10-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conditional", "0002_event_with_speakers_registration_note_speaker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["name"],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ["name"],
                "verbose_name": "registration",
                "verbose_name_plural": "registrations",
            },
        ),
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ["title"],
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="speaker",
            options={
                "ordering": ["name"],
                "verbose_name": "speaker",
                "verbose_name_plural": "speakers",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="company name"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="note"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="vat_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="VAT ID"),
        ),
        migrations.AlterField(
            model_name="session",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="conditional.event",
                verbose_name="event",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers",
                to="conditional.event",
                verbose_name="event",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
    ]
