# Generated by Django 5.2.14 on 2026-07-17 13:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Supplier company name", max_length=200),
                ),
                ("website", models.URLField(blank=True, help_text="Supplier website")),
                (
                    "rating",
                    models.FloatField(default=0.0, help_text="Supplier rating (0-5)"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Full description"),
                ),
                (
                    "sku",
                    models.SlugField(help_text="Stock keeping unit", max_length=40),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Retail price",
                        max_digits=8,
                    ),
                ),
                (
                    "weight_kg",
                    models.FloatField(default=0.0, help_text="Weight in kilograms"),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, help_text="Units in stock"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Available for sale"),
                ),
                ("homepage", models.URLField(blank=True, help_text="Product page")),
                (
                    "release_date",
                    models.DateField(blank=True, help_text="Release date", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, help_text="Record created"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="object_detail.supplier",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="products", to="object_detail.tag"),
                ),
                (
                    "warehouse",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product",
                        to="object_detail.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
