# Generated by Django 5.2.14 on 2026-10-06 09:12

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object_detail", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["name"],
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "ordering": ["code"],
                "verbose_name": "warehouse",
                "verbose_name_plural": "warehouses",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Record created",
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, help_text="Full description", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="homepage",
            field=models.URLField(blank=True, help_text="Product page", verbose_name="homepage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Available for sale", verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="Product name", max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Retail price",
                max_digits=8,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(
                blank=True,
                help_text="Release date",
                null=True,
                verbose_name="release date",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.SlugField(help_text="Stock keeping unit", max_length=40, verbose_name="SKU"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, help_text="Units in stock", verbose_name="stock"),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="object_detail.supplier",
                verbose_name="supplier",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="object_detail.tag",
                verbose_name="tags",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="warehouse",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="object_detail.warehouse",
                verbose_name="warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight_kg",
            field=models.FloatField(default=0.0, help_text="Weight in kilograms", verbose_name="weight (kg)"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(help_text="Supplier company name", max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="rating",
            field=models.FloatField(default=0.0, help_text="Supplier rating (0-5)", verbose_name="rating"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="website",
            field=models.URLField(blank=True, help_text="Supplier website", verbose_name="website"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=60, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="city",
            field=models.CharField(max_length=120, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="country",
            field=models.CharField(max_length=120, verbose_name="country"),
        ),
    ]
