# Generated by Django 5.2.12 on 2026-05-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_campaign_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ("order",), "verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("order",), "verbose_name": "Book", "verbose_name_plural": "Books"},
        ),
        migrations.AlterField(
            model_name="author",
            name="created_dt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="author",
            name="modified_dt",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="author",
            name="pseudonym",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Pseudonym"),
        ),
        migrations.AlterField(
            model_name="bar",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="baz",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.author", verbose_name="Author"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_dt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="book",
            name="modified_dt",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titel"),
        ),
        migrations.AlterField(
            model_name="foo",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateField(verbose_name="Date joined"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="invite_reason",
            field=models.CharField(max_length=64, verbose_name="Invite reason"),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.CreateModel(
            name="BookReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reviewer", models.CharField(max_length=100, verbose_name="Reviewer")),
                ("text", models.TextField(verbose_name="Review Text")),
                ("rating", models.IntegerField(verbose_name="Rating")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="app.book"
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Review",
                "verbose_name_plural": "Book Reviews",
                "ordering": ["-rating"],
            },
        ),
    ]
