# Generated by Django 5.2.14 on 2026-06-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_group_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qux",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("foo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.foo")),
            ],
        ),
    ]
