# Generated by Django 5.2.14 on 2026-06-24 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_qux"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bar",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="baz",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="foo",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="qux",
            options={"ordering": ["name"]},
        ),
    ]
