# Generated by Django 5.2.14 on 2026-07-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_bar_options_alter_baz_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="S3FilePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_s3file", "Can view S3 files"),
                    ("delete_s3file", "Can delete S3 files"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
