# Generated by Django 5.2.14 on 2026-10-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nested", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "company",
                "verbose_name_plural": "companies",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "department",
                "verbose_name_plural": "departments",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["name"],
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
            },
        ),
        migrations.AlterModelOptions(
            name="office",
            options={
                "ordering": ["name"],
                "verbose_name": "office",
                "verbose_name_plural": "offices",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(max_length=100, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="nested.company",
                verbose_name="company",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="nested.department",
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="office",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offices",
                to="nested.company",
                verbose_name="company",
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
    ]
