# Generated by Django 5.2.14 on 2026-10-06 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guardian_demo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["title"],
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="body",
            field=models.TextField(blank=True, verbose_name="body"),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_dt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
    ]
