# Generated by Django 5.2.14 on 2026-10-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("breadcrumbs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={
                "ordering": ["title"],
                "verbose_name": "board",
                "verbose_name_plural": "boards",
            },
        ),
        migrations.AlterModelOptions(
            name="workspace",
            options={
                "ordering": ["name"],
                "verbose_name": "workspace",
                "verbose_name_plural": "workspaces",
            },
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="board",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="breadcrumbs.workspace",
                verbose_name="workspace",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
    ]
