# Generated by Django 5.2.14 on 2026-10-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["title"],
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="created_dt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=10,
                verbose_name="difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="favorite",
            field=models.BooleanField(default=False, verbose_name="favorite"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(default=2, verbose_name="servings"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
    ]
