# Generated by Django 5.2.14 on 2026-07-16 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "vehicle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polymorphic_demo.vehicle",
                    ),
                ),
                ("doors", models.IntegerField(default=4)),
            ],
            options={
                "abstract": False,
            },
            bases=("polymorphic_demo.vehicle",),
        ),
        migrations.CreateModel(
            name="Motorcycle",
            fields=[
                (
                    "vehicle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polymorphic_demo.vehicle",
                    ),
                ),
                ("engine_cc", models.IntegerField(default=600)),
            ],
            options={
                "abstract": False,
            },
            bases=("polymorphic_demo.vehicle",),
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "vehicle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polymorphic_demo.vehicle",
                    ),
                ),
                ("payload_tons", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
            bases=("polymorphic_demo.vehicle",),
        ),
    ]
