# Generated by Django 5.2.14 on 2026-10-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polymorphic_demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "car", "verbose_name_plural": "cars"},
        ),
        migrations.AlterModelOptions(
            name="motorcycle",
            options={
                "verbose_name": "motorcycle",
                "verbose_name_plural": "motorcycles",
            },
        ),
        migrations.AlterModelOptions(
            name="truck",
            options={"verbose_name": "truck", "verbose_name_plural": "trucks"},
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "ordering": ["name"],
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
            },
        ),
        migrations.AlterField(
            model_name="car",
            name="doors",
            field=models.IntegerField(default=4, verbose_name="doors"),
        ),
        migrations.AlterField(
            model_name="motorcycle",
            name="engine_cc",
            field=models.IntegerField(default=600, verbose_name="engine (cc)"),
        ),
        migrations.AlterField(
            model_name="truck",
            name="payload_tons",
            field=models.IntegerField(default=1, verbose_name="payload (tons)"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
    ]
