name: Docs

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - run: 'pip install --require-hashes --only-binary :all: -r docs/requirements.txt'
      - run: mkdocs build --strict
